theme: jekyll-theme-cayman
title: Open Sourced Company
description: 開源公司
google_analytics: UA-140600686-5
splash_btn_text: 查看職缺
job_form_url: https://forms.gle/uuvw3TYH2YpZvT5m9
exam_submit_form_url: https://forms.gle/LW9UAo2YWpUrgFLq6
link_jd_culture: "/principles/principles.html"
link_jd_benefits: "/people/benefits.html"
link_jd_salary: "/people/engineering_level.html"
link_jd_interview_process: "/recruit/interview_process.html"
link_jd_expectations: "/principles/values.html"
link_jd_webdev: "/recruit/webdev.html"
user_g: 升級
user_d: 動物