theme: jekyll-theme-cayman
title: Open Sourced Company
description: Build Extraordinary Products
google_analytics: UA-140600686-5
splash_btn_text: View Opportunities
job_form_url: https://forms.gle/uuvw3TYH2YpZvT5m9
exam_submit_form_url: https://forms.gle/LW9UAo2YWpUrgFLq6
url_jd_culture: "/principles/principles.html"
url_jd_benefits: "/people/benefits.html"
url_jd_salary: "/people/engineering_level.html"
url_jd_interview_process: "/recruit/interview_process.html"
url_jd_expectations: "/principles/values.html"