theme: jekyll-theme-cayman
title: Open Sourced Company
description: Build Extraordinary Products
google_analytics: UA-140600686-5
splash_btn_text: View Opportunities
job_form_url: https://forms.gle/uuvw3TYH2YpZvT5m9
exam_submit_form_url: https://forms.gle/LW9UAo2YWpUrgFLq6
url_jd_culture: "{{ site.baseurl }}/principles/principles.html"
url_jd_benefits: "{{ site.baseurl }}/people/benefits.html"
url_jd_salary: "{{ site.baseurl }}/people/engineering_level.html"
url_jd_interview_process: "{{ site.baseurl}}/recruit/interview_process.html"
url_jd_expectations: "{{ site.baseurl }}/values.html"